repos:
  -   repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
        - id: flake8
  -   repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.32.0
      hooks:
        - id: yapf
          args: ["-i", "-r"]
          files: "python"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
      - id: clang-format
