[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.21",
  "conan@git+https://github.com/gabyx/conan.git@feature/improve-cmakedeps-find-package",
  "markupsafe>=1.1.1,<2.1.0",  # see https://github.com/pallets/markupsafe/issues/284
  "ninja",
  "scikit-build",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
archs = ["auto64"]
test-extras = ["test", "all"]
test-command = "pytest {project}/tests"
# PyPy builds fail with an error about ninja, probably https://github.com/pypa/setuptools/issues/2912
# tbb-devel not available for musllinux
skip = ["pp*", "*musllinux*"]
build-verbosity = 1

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
