[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.18",
  "conan",
  "ninja",
  "scikit-build",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest h5py matplotlib xarray pandas scipy>=1.7.0 pythreejs"
test-command = "pytest {project}/tests"
build = ["cp39-manylinux_x86_64", "cp38-macosx_x86_64", "cp39-win_amd64"]
