[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.18",
  "conan",
  "ninja",
  "scikit-build",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
test-skip = "*"
skip = ["cp36-*", "cp37-*", "cp38-*", "cp310-*", "*-win32", "*-manylinux_i686"]
