[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.18",
  "conan",
  "ninja",
  "scikit-build",
  "tbb-devel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
archs = ["auto64"]
before-build = "rm -rf {project}/build"  # probably https://github.com/pypa/setuptools/issues/2912
test-extras = ["test", "all"]
test-command = "pytest {project}/tests"
skip = ["pp*"]
