[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.21",
  "conan",
  "markupsafe>=1.1.1,<2.1.0",  # see https://github.com/pallets/markupsafe/issues/284
  "ninja",
  "scikit-build",
  "tbb-devel==2021.4.0",  # because of hack with specific cmake config from conda package
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
archs = ["auto64"]
test-extras = ["test", "all"]
test-command = "pytest {project}/tests"
# PyPy builds fail with an error about ninja, probably https://github.com/pypa/setuptools/issues/2912
# tbb-devel not available for musllinux
skip = ["pp*", "*musllinux*"]

[tool.pytest.ini_options]
addopts = "-ra -v"
filterwarnings = [
  'ignore:You are running a "Debug" build of scipp:'
]
testpaths = "tests"
