[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake>=3.21",
  "conan==1.56.0",
  "markupsafe>=1.1.1,<2.1.0",  # see https://github.com/pallets/markupsafe/issues/284
  "ninja",
  "scikit-build==0.13.1",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
archs = ["auto64"]
test-requires = ["scipy", "graphviz", "pooch"]
test-extras = ["test"]
test-command = "pytest --ignore {project}/tests/plotting --ignore {project}/tests/hypothesis/ --ignore {project}/tests/experimental/ {project}/tests"
# PyPy builds fail with an error about ninja, probably https://github.com/pypa/setuptools/issues/2912
# tbb-devel not available for musllinux
skip = ["pp*", "*musllinux*"]
build-verbosity = 1

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.bandit]
# Excluding tests because bandit doesn't like `assert`.
exclude_dirs = ["docs/conf.py", "tests", "install", "conda/cmake-package-test", "tools", "setup.py"]

[tool.codespell]
ignore-words-list = "elemt"
skip = "./.git,./install,./build,./cmake-build*,./lib/cmake/sanitizers-cmake,./.tox,*/*_cache,*/.virtual_documents,*/.ipynb_checkpoints,*.pdf,*.svg"

[tool.isort]
skip_gitignore = true
line_length = 88
multi_line_output = 2  # for compatibility with yapf
skip_glob = ["src/scipp/__init__.py", "src/scipp/core/__init__.py"]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = "tests"
addopts = """
--strict-config
--strict-markers
-ra
-v
"""
filterwarnings = [
  'error',
  'ignore:You are running a "Debug" build of scipp:',
  'ignore:sc.matrix\(\) has been deprecated:DeprecationWarning',
  'ignore:sc.matrices\(\) has been deprecated:DeprecationWarning',
  # Comes from pytest_asyncio and is not our fault.
  "ignore:The 'asyncio_mode' default value will change to 'strict' in future:DeprecationWarning",
  'ignore::scipy.optimize._optimize.OptimizeWarning',
  # Plotting related warnings.
  "ignore:You are using Scipp's deprecated plotting backend:scipp.VisibleDeprecationWarning",
  'ignore:Attempt to set non-positive :UserWarning',
  'ignore:Widget. :DeprecationWarning',
  'ignore:Attempting to set identical low and high ylims makes transformation singular; automatically expanding.:UserWarning',
  # TODO Plotting related deprecation warnings which should be addressed!
  'ignore:NONE is deprecated and will be removed in Pillow 10 \(2023-07-01\). Use Resampling.NEAREST or Dither.NONE instead.:DeprecationWarning',
  'ignore:ADAPTIVE is deprecated and will be removed in Pillow 10 \(2023-07-01\). Use Palette.ADAPTIVE instead.:DeprecationWarning',
  'ignore:\n            Sentinel is not a public part of the traitlets API:DeprecationWarning',
  'ignore:Keyword `trait` is deprecated in traitlets 5.0, use `value_trait` instead:DeprecationWarning',
  'ignore:Keyword `traits` is deprecated in traitlets 5.0, use `per_key_traits` instead:DeprecationWarning',
  'ignore:Support for mapping types has been deprecated and will be dropped in a future release.:DeprecationWarning',
]
