variables:
  - template: variables.yml

jobs:
  - ${{ each py in variables.linux.py_version }}:
    - template: conda_build.yml
      parameters:
        py_version: ${{ py }}
        image: ${{ variables.linux.image }}
        ccache: true
