parameters:
- name: 'platforms'
  type: object
  default:
    linux:
      image: 'ubuntu-20.04'
      py_version: ['3.7']
      publish: 'linux-64'
      params:
        ccache: false
    osx:
      image: 'macOS-10.14'
      py_version: ['3.7']
      publish: 'osx-64'
      params:
        OSX_VERSION: '10.15'
- name: 'deploy'
  type: boolean
  default: false
- name: release
  type: boolean
  default: false

stages:
  - template: code_quality_checks.yml
    parameters:
      image: ${{ parameters.platforms.linux.image }}

  - stage: 'build_and_test'
    displayName: 'Build and Test'
    jobs:
      - ${{ each os in parameters.platforms }}:
        - ${{ each py in os.Value.py_version }}:
          - template: conda_build.yml
            parameters:
              py_version: ${{ py }}
              image: ${{ os.Value.image }}
              publish: ${{ os.Value.publish }}
              ${{ each param in os.Value.params }}:
                ${{ param.Key }}: ${{ param.Value }}

  - template: documentation_build.yml
    parameters:
      image: ${{ parameters.platforms.linux.image }}
      release: ${{ parameters.release }}
      package_name: ${{ parameters.platforms.linux.publish }}-py3.7

  - ${{ if eq(parameters.deploy, true) }}:
    - template: deploy.yml
      parameters:
        image: ${{ parameters.platforms.linux.image }}
        release: ${{ parameters.release }}
        package_list:
          ${{ each os in parameters.platforms }}:
            ${{ each py in os.Value.py_version }}:
              ${{ os.Value.publish }}-py${{ py }}: true
