parameters:
- name: py_version
  type: string
  default: ''
- name: image
  type: string
  default: ''
- name: ccache
  type: boolean
  default: false
- name: OSX_VERSION
  type: string
  default: ''
- name: publish
  type: string
  default: ''

jobs:
  - job:
    timeoutInMinutes: 120
    displayName: ${{ format('{0}-py{1}', parameters.image, parameters.py_version) }}
    pool:
      vmImage: ${{ parameters.image }}
    variables:
      - name: OSX_VERSION
        value: ${{ parameters.OSX_VERSION }}

    steps:
      - checkout: self
        submodules: true

      - ${{ if eq(parameters.ccache, true) }}:
        - template: ccache.yml

      - ${{ if contains(parameters.image, 'windows') }}:
        - powershell: |
            Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
            Write-Host "##vso[task.setvariable variable=conda_dir]$env:CONDA"
          displayName: 'Configure Conda'

      - ${{ if not(contains(parameters.image, 'windows')) }}:
        - bash: |
            echo "##vso[task.prependpath]$CONDA/bin"
            echo "##vso[task.setvariable variable=conda_dir]$CONDA"
          displayName: 'Configure Conda'

      - ${{ if not(eq(length(parameters.OSX_VERSION), 0)) }}:
        - bash: |
            sudo chown -R $USER $CONDA
          displayName: 'Take ownership of Conda installation'

      - bash: |
          set -ex
          conda --version
          conda install --yes conda-build
          conda config --set always_yes yes --set changeps1 no
          conda env create -f scipp-developer.yml
          source activate scipp-developer
          # TODO: source activate does not work (see https://github.com/conda/conda/issues/9566)
          # echo "##vso[task.prependpath]$CONDA/envs/scipp-developer/bin"
          # echo $CONDA_PREFIX
        displayName: 'Setup Conda'
      # - bash: |
      #     set -ex
      #     echo $OSX_VERSION $CONDA $CONDA_PREFIX $PYTHONPATH
      #   displayName: 'Print variables'
      - bash: ./tools/make_and_install.sh
        # env:
        #   CONDA_PREFIX: $CONDA_PREFIX
        displayName: 'Make and Install'
      - bash: |
          conda build --channel conda-forge --python=${{ parameters.py_version }} --no-anaconda-upload ./conda
        env:
          SKIP_BUILD: "ON"
        displayName: 'Build package'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(conda_dir)/conda-bld/${{ parameters.publish }}"
          ArtifactName: "${{ parameters.publish }}-py${{ parameters.py_version }}"
        displayName: 'Publish Conda package artifacts'
