parameters:
  - name: py_version
    type: string
    default: ''
  - name: image
    type: string
    default: ''
  - name: ccache
    type: boolean
    default: false
  - name: OSX_VERSION
    type: string
    default: ''
  - name: label
    type: string
    default: 'dev'
  - name: deploy
    type: boolean
    default: false
  - name: publish
    type: string
    default: ''

jobs:
  - job:
    timeoutInMinutes: 120
    displayName: ${{ format('{0}-py{1}', parameters.image, parameters.py_version) }}
    pool:
      vmImage: ${{ parameters.image }}
    variables:
      - template: variables.yml
      - name: OSX_VERSION
        value: ${{ parameters.OSX_VERSION }}

    steps:
      - checkout: self
        submodules: true

      - ${{ if eq(parameters.ccache, true) }}:
        - template: ccache.yml

      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          echo "##vso[task.setvariable variable=conda_dir]$CONDA"
          sudo chown -R $USER $CONDA
        displayName: 'Configure Conda'
      - bash: |
          set -ex
          conda --version
          conda install --yes anaconda-client conda-build
          conda config --set always_yes yes --set changeps1 no
        displayName: 'Install Conda'
      - ${{ if eq(parameters.deploy, true) }}:
        - bash: |
            conda build --user scipp --token "$ANACONDA_TOKEN" --channel conda-forge --label ${{ parameters.label }} --python=${{ parameters.py_version }} ./conda
          env:
            ANACONDA_TOKEN: $(anaconda_token_secret)
          displayName: 'Package build and deploy'
      - ${{ if not(eq(parameters.deploy, true)) }}:
        - bash: |
            conda build --channel conda-forge --python=${{ parameters.py_version }} ./conda
          displayName: 'Package build'
      - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: "$(conda_dir)/conda-bld/${{ parameters.publish }}"
            ArtifactName: ${{ parameters.publish }}
          displayName: 'Publish Conda package artifacts'
