parameters:
  - name: py_version
    type: string
    default: ''
  - name: image
    type: string
    default: ''
  - name: ccache
    type: boolean
    default: false
  - name: OSX_VERSION
    type: string
    default: ''
  - name: label
    type: string
    default: 'test'
  - name: publish
    type: string
    default: ''

jobs:
  - job:
    timeoutInMinutes: 120
    displayName: ${{ format('{0}-py{1}', parameters.image, parameters.py_version) }}
    pool:
      vmImage: ${{ parameters.image }}
    variables:
      - name: OSX_VERSION
        value: ${{ parameters.OSX_VERSION }}

    steps:
      - checkout: self
        submodules: true

      - ${{ if eq(parameters.ccache, true) }}:
        - template: ccache.yml

      - ${{ if contains(parameters.image, 'windows') }}:
        - powershell: |
            Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
            Write-Host "##vso[task.setvariable variable=conda_dir]$env:CONDA"
          displayName: 'Configure Conda directories'

      - ${{ if not(contains(parameters.image, 'windows')) }}:
        - bash: |
            echo "##vso[task.prependpath]$CONDA/bin"
            echo "##vso[task.setvariable variable=conda_dir]$CONDA"
          displayName: 'Configure Conda'

      - ${{ if not(eq(length(parameters.OSX_VERSION), 0)) }}:
        - bash: |
            sudo chown -R $USER $CONDA
          displayName: 'Take ownership of Conda installation'

      - bash: |
          set -ex
          conda --version
          conda install --yes conda-build
          conda config --set always_yes yes --set changeps1 no
        displayName: 'Install Conda'
      - bash: |
          conda build --user scipp --channel conda-forge --label ${{ parameters.label }} --python=${{ parameters.py_version }} --no-anaconda-upload ./conda
        displayName: 'Build package'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(conda_dir)/conda-bld/${{ parameters.publish }}"
          ArtifactName: "${{ parameters.publish }}-py${{ parameters.py_version }}"
        displayName: 'Publish Conda package artifacts'
