package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - tbb-devel
    # doc build requirements
    - appdirs
    - graphlib-backport # for python < 3.9
    - h5py
    - ipykernel=6.3.1  # issue with pythreejs 3d plotting, see https://github.com/ipython/ipykernel/issues/771
    - ipympl
    - ipywidgets
    - matplotlib-base
    - nbsphinx
    - python-configuration
    - python-graphviz
    - pythreejs
    - pyyaml
    - scipy>=1.7.0
    - sphinx
    - sphinx-book-theme
    - sphinx-copybutton
  run:
    - appdirs
    - numpy>=1.20.0
    - python {{ python }}
    - python-configuration
    - pyyaml
    - tbb
    - graphlib-backport # for python < 3.9

test:
  imports:
    - scipp
  requires:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - h5py
    - ipykernel=6.3.1  # issue with pythreejs 3d plotting, see https://github.com/ipython/ipykernel/issues/771
    - ipympl
    - ipywidgets
    - matplotlib-base
    - pytest
    - pythreejs
    - python-graphviz
    - xarray
    - pandas
    - scipy>=1.7.0
    - tbb-devel
  files:
    - cmake-package-test/
  source_files:
    - tests/
  commands:
    - python -m pytest -v tests
    - python cmake-package-test/build.py

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
   - DOCS_HTML_DIR # [linux]
  script:
    - cmake --preset package-linux [linux]
    - cmake --preset package-macos [osx]
    - cmake --preset package-windows [win]
    - cmake --build --preset build
    - cmake --build --preset docs [linux]
    - cmake --build --preset linkcheck [linux]
    - cp -r build/html $DOCS_HTML_DIR [linux]
    - ctest --preset test


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
