package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - tbb-devel
  run:
    - appdirs
    - numpy>=1.20.0
    - python {{ python }}
    - python-configuration
    - pyyaml
    - tbb
    - graphlib-backport # for python < 3.9

test:
  imports:
    - scipp
  requires:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - h5py
    - ipykernel = 6.3.1  # issue with pythreejs 3d plotting, see https://github.com/ipython/ipykernel/issues/771
    - ipympl
    - ipywidgets
    - matplotlib-base
    - pytest
    - pythreejs
    - python-graphviz
    - xarray
    - pandas
    - scipy>=1.7.0
    - tbb-devel
    - pandoc
    - sphinx = 4.2.0
    - sphinx-book-theme
    - sphinx-copybutton
    - nbsphinx
  files:
    - cmake-package-test/
  source_files:
    - tests/
    - docs/
    - .git/  # Docs build uses git to determine version and release month
  script_env:
    - DOCS_BUILD_DIR
  commands:
    - python -m pytest -v tests
    - python cmake-package-test/build.py
    - python docs/build_and_test.py [linux64]

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - OSX_VERSION [osx]
    - CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
  script:
    - python tools/build_cpp.py


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
