trigger:
  branches:
    exclude:
      - '*'

pr: none

schedules:
  - cron: "0 1 * * *"
    displayName: 'Nightly debug builds'
    branches:
      include:
        - 'main'
    always: true


extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    env:
      SCIPP_DEBUG_BUILD: 1
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scipp-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-minimal.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-minimal.yml'
    deploy: false
    conda_label: 'main'
    release: false
