parameters:
- name: debug
  displayName: Debug
  type: boolean
  default: false

trigger:
  - main

pr: none

extends:
  template: templates/stages.yml
  parameters:
    debug: ${{ parameters.debug }}
    py_versions:
      linux: ['3.7']
      osx: ['3.7']
      windows: ['3.7']
    deploy: true
    conda_label: 'dev'
