parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  - main

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    py_versions:
      linux: ['3.7']
      osx: ['3.7']
      windows: ['3.7']
    deploy: true
    conda_label: 'dev'
