parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scipp > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: refs/tags/3.0.0

trigger:
  tags:
    include:
      - '*.*.*'

schedules:
  - cron: "0 0 * * *"
    displayName: 'Nightly dev build'
    branches:
      include:
        - 'main'
    always: false


pr: none


extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.7', '3.8', '3.9']
        conda_env: 'scipp-developer.yml'
      osx:
        py_versions: ['3.7', '3.8', '3.9']
        conda_env: 'scipp-developer-minimal.yml'
      windows:
        py_versions: ['3.7', '3.8', '3.9']
        conda_env: 'scipp-developer-minimal.yml'
    package: true
    deploy: true
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  # nightly
      conda_label: 'dev'
    ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  # tagged release
      conda_label: 'main'
      release: true
