trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/build_and_package.yml
  parameters:
    py_versions:
      linux: ['3.7']
      osx: ['3.7']
      # windows: ['3.7']
    deploy: false


      # linux: ['3.6', '3.7']
