trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/build_and_package.yml
  parameters:
    platforms:
      linux:
        py_version: ['3.6', '3.7']
