parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scipp-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-minimal.yml'
