parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    py_versions:
      linux: ['3.7']
      osx: ['3.7']
      windows: ['3.7']
