trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/build_and_package.yml



  # - stage: 'post_build_checks'
  #   displayName: 'Post Build Checks'

  #   jobs:
  #     - template: templates/documentation_build.yml
  #     - template: templates/test_can_install_and_import.yml