trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/stages.yml
  parameters:
    py_versions:
      linux: ['3.7', '3.6']
      osx: ['3.7', '3.6']
      windows: ['3.7', '3.6']
    deploy: true
    label: 'test'
