parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    py_versions:
      linux: ['3.7', '3.8']
      osx: ['3.7', '3.8']
      windows: ['3.7', '3.8']
    deploy: true
    conda_label: 'main'
    release: true
    conda_env: 'scipp-developer-minimal.yml'
