parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    py_versions:
      linux: ['3.7', '3.8']
      osx: ['3.7', '3.8']
      windows: ['3.7', '3.8']
    deploy: true
    conda_label: 'main'
    release: true
