trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/stages.yml
  parameters:
    py_versions:
      linux: ['3.7', '3.8']
      osx: ['3.7', '3.8']
      windows: ['3.7', '3.8']
    deploy: true
    label: 'main'
    release: true
