parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scipp > Settings > Service connections

# TODO revert

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: units-conan

trigger:
  branches:
    exclude:
      - '*'

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.9']
        conda_env: 'scipp-developer.yml'
      osx:
        py_versions: ['3.9']
        conda_env: 'scipp-developer-minimal.yml'
      windows:
        py_versions: ['3.9']
        conda_env: 'scipp-developer-minimal.yml'
    deploy: true
    conda_label: 'test'
    release: false
    publish_docs: false
