name: Package build (nightly and release)

on:
  pull_request:  # TODO temporary for setting up

jobs:
  conda_build:
    name: Package build (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --yes conda-build
      - run: conda build --channel conda-forge --python=${{ matrix.python-version }} --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          path: conda/package/*/scipp*.tar.bz2

      - uses: actions/upload-artifact@v2
        if: ${{ contains(matrix.os, 'ubuntu') && matrix.python-version == '3.7' }}
        with:
          name: DocumentationHTML
          path: docs_html

  deploy:
    needs: conda_build
    name: Deploy packages and docs
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --yes anaconda-client
      - uses: actions/download-artifact@v2
      - run: ls -R

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master
          repository-name: scipp/scipp.github.io
          #ssh-key: ${{ secrets.DEPLOY_KEY }}
          folder: DocumentationHTML
          single-commit: true
          dry-run: true
          clean: true
          clean-exclude: |
            .nojekyll
            release/*
