name: Package build (nightly and release)

on:
  pull_request:  # TODO temporary for setting up
  create:
    tags:
      - "*.*.*"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  conda_build:
    name: Package build (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --yes conda-build
      - run: conda build --channel conda-forge --python=${{ matrix.python-version }} --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v2
        with:
          name: conda-package-${{ matrix.os }}-py${{ matrix.python-version }}
          path: conda/package/*/scipp*.tar.bz2

      - uses: actions/upload-artifact@v2
        if: ${{ contains(matrix.os, 'ubuntu') && matrix.python-version == '3.7' }}
        with:
          name: html
          path: docs_html

  deploy:
    needs: conda_build
    name: Deploy packages and docs
    runs-on: ubuntu-latest
    env:
      conda_label: ${{ startsWith(github.ref, 'refs/tags/') && 'testrelease' || 'testdev' }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -c conda-forge --yes anaconda-client
      - uses: actions/download-artifact@v2
      - run: anaconda --token ${{ secrets.ANACONDATOKEN }} upload --user scipp --label ${{ env.conda_label }} $(ls conda-package-*/*/*.tar.bz2)

      - uses: actions/checkout@v2
        with:
          repository: scipp/scipp.github.io
          path: pages

      - if: ${{ env.conda_label == 'testdev' }}  # TODO label inverted for testing
        run: |
          mkdir -p html/release/dummy
          echo ${GITHUB_REF#refs/tags/}
          cp -r html/* html/release/dummy/

  deploy_test:
    name: Test docs deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir html
          echo "<html>deploy test</html>" > html/index.html
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: SimonHeybrock/scipp.github.io
          branch: master
          ssh-key: ${{ secrets.DEPLOY_TEST }}
          folder: html
          single-commit: true
          clean-exclude: release
