name: PR and main CI

on: 
  schedule:
    - cron: '0 1 * * *'
  pull_request:
  

jobs:
  build_and_test:
    name: CI (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
        include:
        - os: ubuntu-latest
          cmake-preset: ci-linux
        - os: macos-latest
          cmake-preset: ci-macos
        - os: windows-latest
          cmake-preset: ci-windows

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - name: Setup env variables
        run: |
          echo "PYTHONPATH=$(pwd)/install" >> $GITHUB_ENV

      - name: ccache
        if: contains(matrix.os, 'ubuntu')
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 1000M

      - name: Setup Mambaforge and dev env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.os == 'ubuntu-latest' && 'scipp-developer.yml' || 'scipp-developer-minimal.yml' }}
          activate-environment: scipp-developer
          auto-activate-base: false

      - name: Run cmake
        shell: bash -l {0}
        run: cmake --preset ${{ matrix.cmake-preset }}
      - name: C++ build
        shell: bash -l {0}
        run: cmake --build --preset ${{ matrix.cmake-preset }}
      - name: C++ tests
        shell: bash -l {0}
        run: ctest --preset ${{ matrix.cmake-preset }}
