name: Release package build

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  conda_build:
    name: Package build (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --yes conda-build
      - run: conda build --channel conda-forge --python=${{ matrix.python-version }} --override-channels --output-folder conda/package --token ${{ secrets.ANACONDATOKEN }} --user scipp --label staging conda

  docs:
    needs: conda_build
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Need to checkout repo so github-pages-deploy-action works
      - name: Setup Mambaforge and dev env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: "3.8"
          environment-file: developer-extra.yml
          activate-environment: developer-extra
          auto-activate-base: false
      - run: mamba install --yes -c scipp/label/staging scipp
      - run: cmake --build --preset docs
      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: build/html/

  deploy:
    needs: docs
    name: Deploy docs and re-label conda packages to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Need to checkout repo so github-pages-deploy-action works
      - uses: actions/download-artifact@v2

      # TODO: can we have multiple target folders so that we don't have the action twice?

      # Push pages once to the top level folder
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          repository-name: scipp/scipp.github.io
          branch: master
          folder: html
          single-commit: true
          clean-exclude: release
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}

      # Push pages a second time to the release folder
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          repository-name: scipp/scipp.github.io
          branch: master
          folder: html
          target-folder: ${{ format('release/{0}', github.ref_name) }}
          single-commit: true
          clean-exclude: release
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}

      # Change conda packages labels from staging to main
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -c conda-forge --yes anaconda-client
      - run: anaconda --token ${{ secrets.ANACONDATOKEN }} move --from-label staging --to-label main scipp/scipp/${{ github.ref_name }}
