name: Test wheel build with mamba

on:
  pull_request:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels for ${{matrix.arch}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            INCLUDE_DIR: "/home/runner/micromamba/envs/build/include"
            LIB_DIR: "/home/runner/micromamba/envs/build/lib"
          - os: macos-14
            arch: arm64
            INCLUDE_DIR: "/Users/runner/micromamba/envs/build/include"
            LIB_DIR: "/Users/runner/micromamba/envs/build/lib"
          - os: macos-13
            arch: x86_64
            INCLUDE_DIR: "/Users/runner/micromamba/envs/build/include"
            LIB_DIR: "/Users/runner/micromamba/envs/build/lib"
          - os: windows-latest
            arch: win_amd64
            INCLUDE_DIR: "C:\\Users\\runneradmin\\micromamba\\envs\\build\\Library\\include"
            LIB_DIR: "C:\\Users\\runneradmin\\micromamba\\envs\\build\\Library\\lib"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: 3.11

      - name: Setup Micromamba Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }} benchmark=1.6.1 gtest=1.15.2 gmock=1.15.2 eigen=3.4.0 libboost-headers=1.86.0 --channel conda-forge

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade cibuildwheel delvewheel

      - name: Build Wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "pp* cp36-* cp37-* cp38-* cp39-* cp310-* *-musllinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_BUILD: "cp310*${{ matrix.arch }} cp311*${{ matrix.arch }} cp312*${{ matrix.arch }}"
          CIBW_TEST_REQUIRES: pytest
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CIBW_ENVIRONMENT_WINDOWS: >
            PATH="C:\\Users\\runneradmin\\micromamba\\envs\\build\\Library\\bin;${PATH}"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
            delvewheel show {wheel}
            && delvewheel repair -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: >
            python -c "import scipp; print(scipp.__version__)"
          CIBW_BUILD_FRONTEND: 'pip; args: --global-option=build_ext --global-option=-I${{ matrix.INCLUDE_DIR }} --global-option=-L${{ matrix.LIB_DIR }}'
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            DYLD_LIBRARY_PATH=/Users/runner/micromamba/envs/build/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}

      - uses: actions/upload-artifact@v4
        with:
          name: pypi-artifacts-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/wheelhouse/*.whl

  show-artifacts:
    needs: [build_wheels]
    name: "Show artifacts"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pypi-artifacts*
          path: ${{ github.workspace }}/dist
          merge-multiple: true

      - shell: bash
        run: |
          ls -lh ${{ github.workspace }}/dist
