name: Weekly package builds

on:
  pull_request:  # temp for testing
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # every Saturday at midnight

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  build_conda:
    name: Package build (${{ matrix.variant.target }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.variant.os }}
    strategy:
      matrix:
        variant:
          - {os: ubuntu-20.04, target: linux_64}
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - uses: conda-incubator/setup-miniconda@v2
      - run: >
          conda install
          --channel conda-forge
          --channel nodefaults
          --yes
          conda-build conda-forge-pinning
      - run: >
          conda build
          --channel conda-forge
          --variant-config-files=${CONDA_PREFIX}/conda_build_config.yaml
          --variant-config-files=${GITHUB_WORKSPACE}/conda/variants/${{ matrix.variant.target }}.yaml
          --python="${{ matrix.python-version }}.* *_cpython"
          --no-anaconda-upload
          --override-channels
          --output-folder conda/package conda

      - uses: actions/upload-artifact@v3
        with:
          name: conda-package-${{ matrix.variant.os }}-py${{ matrix.python-version }}
          path: conda/package/*/scipp*.tar.bz2

  build_wheels:
    name: Wheels on ${{ matrix.os }}-${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        build: [cp38, cp311]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0  # history required so cmake can determine version

    - uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_BUILD: ${{ matrix.build }}-*
        MACOSX_DEPLOYMENT_TARGET: "10.15"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: wheelhouse/*.whl