name: Weekly package builds

on:
  pull_request:  # temp for testing
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # every Saturday at midnight

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  build_conda:
    name: Package build (${{ matrix.variant.target }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.variant.os }}
    strategy:
      matrix:
        variant:
          - {os: ubuntu-20.04, target: linux_64}
        python-version: ["3.8", "3.10"]

    steps:
    - uses: ./.github/workflows/conda.yml
      with:
        os: ${{ matrix.variant.os }}
        target: ${{ matrix.variant.target }}
        python-version: ${{ matrix.python-version }}

  build_wheels:
    name: Wheels on ${{ matrix.os }}-${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        build: [cp38, cp311]

    steps:
    - uses: ./.github/workflows/wheel.yml
      with:
        os: ${{ matrix.os }}
        build: ${{ matrix.build }}