name: Wheel build

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system: ubuntu-24.04, macos-14, or windows-2022'
        required: true
        type: string
      build:
        description: "Wheel build variant such as cp312"
        required: true
        type: string

jobs:
  build_wheels:
    name: Wheels on ${{ inputs.os }}-${{ inputs.build }}
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0  # history required so cmake can determine version
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: "3.10"

    - name: Setup Micromamba Python 3.10
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: build
        init-shell: bash
        create-args: >-
          python=3.10 benchmark=1.6.1 gtest=1.15.2 gmock=1.15.2 eigen=3.4.0 libboost-headers=1.86.0 --channel conda-forge

    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade cibuildwheel delvewheel
    - name: Build Wheels
      run: cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: ${{ inputs.build }}-*
        MACOSX_DEPLOYMENT_TARGET: "11.0"
        CIBW_BUILD_FRONTEND: 'pip; args: --global-option=build_ext --global-option=-I"/home/runner/micromamba/envs/build/include" --global-option=-L"/home/runner/micromamba/envs/build/lib"'

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ inputs.os }}-${{ inputs.build }}
        path: wheelhouse/*.whl
