name: Wheel build

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system: ubuntu-22.04, macos-14, or windows-2019'
        required: true
        type: string
      build:
        description: "Wheel build variant such as cp312"
        required: true
        type: string

jobs:
  build_wheels:
    name: Wheels on ${{ inputs.os }}-${{ inputs.build }}
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0  # history required so cmake can determine version

    - uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_BEFORE_ALL: |
          echo "Installing miniforge to setup conda for cpp deps"
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3-$(uname)-$(uname -m).sh -b -p /opt/miniconda
          conda install -y --no-deps benchmark=1.6.1 gtest=1.15.2 gmock=1.15.2 libboost-headers=1.86.0 eigen=3.4.0 pybind11=2.13.6
        CIBW_BUILD: ${{ inputs.build }}-*
        MACOSX_DEPLOYMENT_TARGET: "11.0"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ inputs.os }}-${{ inputs.build }}
        path: wheelhouse/*.whl
